name: waggs_app
version: 1.0.1+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_cli: ^1.8.1
  google_fonts:
  get_storage: ^2.0.3
  otp_text_field:
  dio: ^4.0.6
  image_picker: ^0.8.5+3
  get_it: ^7.2.0
  pull_to_refresh: ^2.0.0
  intl_phone_field:
  cached_network_image:
  syncfusion_flutter_sliders:
  flutter_rating_bar: ^4.0.1
  otp_timer_button: ^1.1.0
  flutter_time_picker_spinner: ^2.0.0
  flutter_image_slideshow: ^0.1.2
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  syncfusion_flutter_datepicker: ^20.2.48
  google_sign_in:
  carousel_slider:
  linkedin_login: ^2.2.1
  flutter_facebook_auth: ^3.1.0
  razorpay_flutter:
  date_time_picker: ^2.1.0
  flutter_svg: ^1.1.3
  geolocator: ^9.0.1
  geocoding: ^2.0.5
  grouped_list: ^5.1.2
  geocode:
  shared_preferences: ^2.0.15
  http:
  permission_handler: ^10.0.0
  location: ^4.2.0
  intl:
  url_launcher:
  sign_in_with_apple: ^4.2.0
  app_tracking_transparency: ^2.0.3
  crypto: ^3.0.1
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter


flutter: 
  uses-material-design: true
  assets:
    - assets/
